name: coolsnowwolf/lede

on:
  schedule:
    - cron: '50 * * * *'

jobs:
  sync:
    name: Sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: 'coolsnowwolf/lede'
          fetch-depth: 5
      - name: User Name
        run: git config user.email "$USER@$HOSTNAME" && git config user.name "$USER"
      - name: Config DownStream
        run: git remote add downstream "$PUSH_TARGET_PREFIX/lede.git"
        env:
          PUSH_TARGET_PREFIX: ${{ secrets.PUSH_TARGET_PREFIX }}
      - name: Push DownStream
        run: git push downstream

