name: coolsnowwolf/lede

on:
  schedule:
    - cron: '50 * * * *'

jobs:
  sync:
    name: Sync
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        run: git clone --mirror --no-single-branch --depth=5 $SRC_REPO repo.git
        env:
          SRC_REPO: https://github.com/coolsnowwolf/lede.git
      - name: Config DownStream
        run: git -C repo.git remote add downstream "$PUSH_TARGET_PREFIX/lede.git"
        env:
          PUSH_TARGET_PREFIX: ${{ secrets.PUSH_TARGET_PREFIX }}
      - name: Push DownStream
        run: git -C repo.git push downstream

