name: openwrt/openwrt

on:
  push:
    paths:
      - '.github/workflows/openwrt+openwrt.yaml'
  schedule:
    - cron: '22 * * * *'

jobs:
  sync:
    name: Sync
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        run: git clone --mirror --no-single-branch --depth=$DEPTH $SRC_REPO repo.git
        env:
          SRC_REPO: https://github.com/openwrt/openwrt.git
          DEPTH: 20
      - name: Config DownStream
        run: git -C repo.git remote add downstream "$PUSH_TARGET"
        env:
          PUSH_TARGET: ${{ secrets.PUSH_TARGET_PREFIX }}/openwrt.git
      - name: Push DownStream
        run: git -C repo.git push downstream

