name: openwrt/openwrt

on:
  watch:
    types: [started]
  schedule:
    - cron: '22 * * * *'

jobs:
  sync:
    name: Sync
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        run: git clone --mirror --no-single-branch --depth=$DEPTH $SRC_REPO repo.git
        env:
          SRC_REPO: https://github.com/openwrt/openwrt.git
          DEPTH: 20
      - name: Config DownStream
        run: git -C repo.git remote add downstream "$PUSH_TARGET"
        env:
          PUSH_TARGET: ${{ secrets.PUSH_TARGET_PREFIX }}/openwrt.git
      - name: Push DownStream
        run: git -C repo.git push --all downstream && git -C repo.git push --tags downstream
      - name: Try Unshallow On Failed
        if: failure()
        run: |
          git -C repo.git fetch --unshallow || exit 1 
          git -C repo.git gc
          git -C repo.git count-objects -vH
          git -C repo.git push --all downstream && git -C repo.git push --tags downstream

